// Naive UI 主题：沿用旧版 PHP UI 配色（米色背景 + 深藏青 + 蓝/青主色）
export const themeOverrides = {
  common: {
    primaryColor: '#3498db',
    primaryColorHover: '#2980b9',
    primaryColorPressed: '#21618c',
    primaryColorSuppl: '#2980b9',
    infoColor: '#33afcd',
    infoColorHover: '#2b9ab5',
    infoColorPressed: '#23829a',
    infoColorSuppl: '#2b9ab5',
    successColor: '#33afcd',
    errorColor: '#e74c3c',
    errorColorHover: '#c0392b',
    errorColorPressed: '#922b21',
    errorColorSuppl: '#c0392b',
    warningColor: '#e67e22',
    bodyColor: '#faf6ef',
    cardColor: '#ffffff',
    popoverColor: '#ffffff',
    modalColor: '#ffffff',
    tableColor: '#ffffff',
    textColorBase: '#10263b',
    textColor1: '#10263b',
    textColor2: '#10263b',
    textColor3: '#707d89',
    borderColor: '#cfd4d8',
    dividerColor: '#e0e6ed',
    borderRadius: '8px',
    borderRadiusSmall: '5px',
    fontWeightStrong: '600',
  },
};
